name: PICARTO
plugin: ./lib/plugins/basic
siteUrl: https://picarto.tv/
urlback: ""
enable: true
m3u8fetch: scripts/m3u8_streamlink.sh
recorder: scripts/record_streamlink.sh
scanInterval: 300
batchSize: 5
streamers: []
